apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  template:
    spec:
      containers:
      - name: mongodb
        image: mongo:latest

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb-deployment
  ports:
    - port: 27017
      targetPort: 27017

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodb-ingress

spec:
  rules:
  - host: mongodb.example.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: mongodb-service
            port:
              number: 27017
