apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  template:
    spec:
      containers:
      - name: mysql
        image: mysql:latest

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-deployment
  ports:
    - port: 3306
      targetPort: 3306

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysql-ingress
spec:
  rules:
  - host: mysql.example.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: mysql-service
            port:
              number: 3306
